export const carMakes = [
  { value: "Buick", label: "Buick" },
  { value: "Volvo", label: "Volvo" },
  { value: "HUMMER", label: "HUMMER" },
  { value: "Subaru", label: "Subaru" },
  { value: "Mitsubishi", label: "Mitsubishi" },
  {
    value: "Mercedes-Benz",
    label: "Mercedes-Benz",
  },
  { value: "Nissan", label: "Nissan" },
  { value: "Lincoln", label: "Lincoln" },
  { value: "GMC", label: "GMC" },
  { value: "Hyundai", label: "Hyundai" },
  { value: "MINI", label: "MINI" },
  { value: "Bentley", label: "Bentley" },
  { value: "Aston Martin", label: "Aston Martin" },
  { value: "Pontiac", label: "Pontiac" },
  { value: "Lamborghini", label: "Lamborghini" },
  { value: "Audi", label: "Audi" },
  { value: "BMW", label: "BMW" },
  { value: "Chevrolet", label: "Chevrolet" },
  { value: "Chrysler", label: "Chrysler" },
  { value: "Kia", label: "Kia" },
  {
    value: "Land",
    label: "Land",
  },
];
export const prices = [
  { value: "$30", label: "$30" },
  { value: "$40", label: "$40" },
  { value: "$50", label: "$50" },
  { value: "$60", label: "$60" },
  { value: "$70", label: "$70" },
  { value: "$80", label: "$80" },
  { value: "$90", label: "$90" },
  { value: "$100", label: "$100" },
  { value: "$200", label: "$200" },
  { value: "$300", label: "$300" },
  { value: "$400", label: "$400" },
  { value: "$500", label: "$500" },
];
